name: "water_party"
description: "Matchmaking parties."
publish_to: 'none'
version: 1.0.5

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_card_swiper: ^7.2.0
  glassmorphism: ^3.0.0
  lucide_icons: ^0.257.0
  flutter_riverpod: ^3.2.1
  uuid: ^4.5.2
  http: ^1.2.1
  web_socket_channel: ^3.0.1
  font_awesome_flutter: ^10.7.0
  geolocator: ^13.0.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  sqflite: ^2.4.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Frutiger
      fonts:
        - asset: assets/fonts/neuefrutiger.ttf
